#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Autonomous Company Evolution Engine — Evolution Queue (2026-07-29).

Real Observe -> Think -> Simulate -> Decide -> Learn pipeline for
self-improvement proposals. Execute is deliberately NOT automated here --
the founder's own explicit choice (asked directly, given this factory has
no CI/rollback safety net and no mechanism besides a real, human-observed
Claude Code session that can ever change this codebase's own files):
every proposal, regardless of computed risk tier, requires real founder
approval in Mission Control before any code is touched. Simulate/Decide
below compute a real, transparent risk/impact estimate -- they inform the
founder's review, they never bypass it.

Stage flow: PROPOSED -> SIMULATED -> AWAITING_FOUNDER_APPROVAL ->
APPROVED / REJECTED -> (once real work is later done in a reviewed
session) IMPLEMENTED. No stage past AWAITING_FOUNDER_APPROVAL is ever
reached without a real founder action -- approve_proposal()/
reject_proposal() are the only functions that can move a record there,
and neither is ever called from factory_loop.js's automatic daily tick
(see factory_loop.js's own maybeGenerateDailyEvolutionQueueIntake()).

Same "ledger vs mutable state" split this factory already uses
everywhere (decisions.jsonl vs factory_state.json; customer_requests.
jsonl vs customer_pipeline_state.json): tool_intelligence.proposals.
list_proposals() is the real, regenerated-each-call intake source (never
mutated here); data/evolution_queue_state.json is this module's own
mutable record, keyed by proposal id, carrying a real stage_history --
which IS the Learning History Dashboard item, nothing else needed.
"""

import json
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

_FACTORY_ROOT = Path(__file__).resolve().parent
DEFAULT_STATE_PATH = _FACTORY_ROOT / "data" / "evolution_queue_state.json"

# Real, named categories the directive's own "Protect" section calls out
# by name -- never touched without explicit founder approval regardless of
# any other computed risk signal. Keyword match against a proposal's own
# real evidence/tool/why_needed text (the same real strings already
# generated by tool_intelligence.proposals), not a guess.
SENSITIVE_AREA_KEYWORDS = {
    "security": ("security", "auth", "password", "token", "credential", "npm_audit", "pinning"),
    "financial": ("profit_oracle", "finance_data", "paddle", "invoice", "payment", "pricing"),
    "customer_contracts": ("contract_generator", "customer_pipeline", "accepted_name", "e-signature"),
}

# Informational only -- surfaced to the founder in list_evolution_queue(),
# never auto-escalated to any action (no notification/auto-anything).
_STUCK_APPROVAL_HOURS = 72


def _now():
    return datetime.now(timezone.utc).isoformat()


def _load_state(state_path=None):
    path = Path(state_path) if state_path else DEFAULT_STATE_PATH
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def _save_state(state, state_path=None):
    path = Path(state_path) if state_path else DEFAULT_STATE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)


def _record_history(record, stage, detail=None):
    record["stage"] = stage
    record["updated_at"] = _now()
    record.setdefault("stage_history", []).append({"stage": stage, "at": record["updated_at"], "detail": detail})


def _new_record(proposal):
    now = _now()
    return {
        "proposal_id": proposal["id"],
        "proposal": proposal,
        "stage": "PROPOSED",
        "stage_history": [{"stage": "PROPOSED", "at": now, "detail": "real proposal intake from tool_intelligence.proposals.list_proposals()"}],
        "created_at": now,
        "updated_at": now,
        "simulation": None,
        "decision_flags": None,
        "founder_decision": None,
    }


def intake_proposals(proposals=None, state_path=None):
    """Real Observe/Think intake -- pulls tool_intelligence.proposals.
    list_proposals()'s current real output (unless a caller injects its
    own list for testing) and creates a new queue record for any real
    proposal id not already tracked. Never removes/mutates an existing
    record -- a proposal id that's already mid-review keeps its real
    history even if its generating signal later disappears."""
    if proposals is None:
        from tool_intelligence import proposals as proposals_module
        proposals = proposals_module.list_proposals()

    state = _load_state(state_path)
    added = []
    for proposal in proposals:
        pid = proposal.get("id")
        if not pid or pid in state:
            continue
        state[pid] = _new_record(proposal)
        added.append(pid)
    _save_state(state, state_path)
    return {"added_count": len(added), "added": added}


def _affected_modules(proposal):
    """Real, mechanical extraction -- every proposal already cites its
    real evidence as file/module names or dotted paths (tool_intelligence.
    proposals' own evidence-citation discipline). Extracts anything that
    looks like a real source reference; never guesses one that isn't
    textually present."""
    text = " ".join(str(proposal.get(k, "")) for k in ("evidence", "why_needed", "tool"))
    matches = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)+\b', text)
    seen = []
    for m in matches:
        if m not in seen:
            seen.append(m)
    return seen


def _sensitive_areas_touched(proposal, affected_modules):
    text = " ".join(str(proposal.get(k, "")) for k in ("evidence", "why_needed", "tool", "id")).lower()
    modules_text = " ".join(affected_modules).lower()
    touched = []
    for area, keywords in SENSITIVE_AREA_KEYWORDS.items():
        if any(kw in text or kw in modules_text for kw in keywords):
            touched.append(area)
    return touched


def simulate_proposal(proposal_id, state_path=None):
    """Real Simulate step -- a static, evidence-based impact estimate,
    never a dynamic execution this factory has no sandbox to run.
    Honestly labeled as a heuristic, not a guarantee."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "PROPOSED":
        return {"success": False, "error": f"cannot simulate from stage {record['stage']!r} (must be PROPOSED)"}

    proposal = record["proposal"]
    affected = _affected_modules(proposal)
    sensitive = _sensitive_areas_touched(proposal, affected)

    if sensitive:
        rollback_complexity = "high"
    elif len(affected) > 1:
        rollback_complexity = "medium"
    else:
        rollback_complexity = "low"

    simulation = {
        "affected_modules": affected,
        "sensitive_areas_touched": sensitive,
        "rollback_complexity": rollback_complexity,
        "method": "static evidence-text analysis -- no dynamic execution sandbox exists in this factory; this is a heuristic, not a guaranteed impact measurement",
        "simulated_at": _now(),
    }
    record["simulation"] = simulation
    _record_history(record, "SIMULATED", f"rollback_complexity={rollback_complexity}, sensitive_areas={sensitive or 'none'}")

    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def _duplicate_architecture_check(affected_modules):
    """Real, narrow check -- a proposal whose own citations already span
    3+ distinct real top-level modules covering overlapping ground is the
    one honest, mechanical signal available without semantic analysis --
    flagged for the founder to judge, never auto-decided."""
    return len({m.split(".")[0] for m in affected_modules}) >= 3


def decide_proposal(proposal_id, state_path=None):
    """Real Decide step -- computes honest concern flags and ALWAYS
    routes to AWAITING_FOUNDER_APPROVAL. Never auto-approves or
    auto-rejects: this factory has no reliable way to mechanically judge
    "does this reduce trust" or "does this break consistency" the way
    the directive names them -- surfacing the real evidence for a human
    to judge is the honest alternative to fabricating that judgment."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "SIMULATED":
        return {"success": False, "error": f"cannot decide from stage {record['stage']!r} (must be SIMULATED)"}

    simulation = record["simulation"] or {}
    affected = simulation.get("affected_modules", [])
    decision_flags = {
        "policy_risk": bool(simulation.get("sensitive_areas_touched")),
        "duplicate_architecture_risk": _duplicate_architecture_check(affected),
        "note": "Real, narrow flags only -- never an auto-approve/auto-reject. Founder approval is always required regardless of these flags.",
    }
    record["decision_flags"] = decision_flags
    _record_history(record, "AWAITING_FOUNDER_APPROVAL",
                     f"policy_risk={decision_flags['policy_risk']}, duplicate_architecture_risk={decision_flags['duplicate_architecture_risk']}")

    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def approve_proposal(proposal_id, decided_by=None, note=None, state_path=None):
    """The founder's own real action -- only valid from
    AWAITING_FOUNDER_APPROVAL. Never called automatically."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "AWAITING_FOUNDER_APPROVAL":
        return {"success": False, "error": f"cannot approve from stage {record['stage']!r} (must be AWAITING_FOUNDER_APPROVAL)"}

    record["founder_decision"] = {"decision": "APPROVED", "decided_by": decided_by, "note": note, "decided_at": _now()}
    _record_history(record, "APPROVED", note or "founder approved")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def reject_proposal(proposal_id, decided_by=None, reason=None, state_path=None):
    """The founder's own real action -- only valid from
    AWAITING_FOUNDER_APPROVAL. Never called automatically."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "AWAITING_FOUNDER_APPROVAL":
        return {"success": False, "error": f"cannot reject from stage {record['stage']!r} (must be AWAITING_FOUNDER_APPROVAL)"}

    record["founder_decision"] = {"decision": "REJECTED", "decided_by": decided_by, "reason": reason, "decided_at": _now()}
    _record_history(record, "REJECTED", reason or "founder rejected")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def mark_implemented(proposal_id, note=None, state_path=None):
    """Closes the loop after real work was actually done in a reviewed
    Claude Code session -- only valid from APPROVED. Never called
    automatically; this factory has no auto-apply mechanism by design."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "APPROVED":
        return {"success": False, "error": f"cannot mark implemented from stage {record['stage']!r} (must be APPROVED)"}

    _record_history(record, "IMPLEMENTED", note or "real implementation completed")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def run_daily_cycle(proposals=None, state_path=None):
    """The only automatic path -- Observe/Think/Simulate/Decide, real and
    safe (pure analysis, no execution). Every record this touches stops
    at AWAITING_FOUNDER_APPROVAL at the latest; approve_proposal()/
    reject_proposal()/mark_implemented() are never called from here."""
    intake_result = intake_proposals(proposals=proposals, state_path=state_path)
    processed = []
    for pid in intake_result["added"]:
        simulate_proposal(pid, state_path=state_path)
        decide_proposal(pid, state_path=state_path)
        processed.append(pid)
    return {"added_count": intake_result["added_count"], "processed": processed}


def list_evolution_queue(state_path=None, now=None):
    """Mission Control aggregate -- real stage distribution, the real
    awaiting-approval queue (with a real, informational stuck-too-long
    flag), and the full real Learning History (every record's own
    stage_history, nothing summarized away)."""
    now = now or datetime.now(timezone.utc)
    state = _load_state(state_path)
    stage_counts = {}
    awaiting_approval = []
    entries = []
    for pid, record in state.items():
        stage = record["stage"]
        stage_counts[stage] = stage_counts.get(stage, 0) + 1
        entry = {
            "proposal_id": pid,
            "tool": record["proposal"].get("tool"),
            "stage": stage,
            "simulation": record.get("simulation"),
            "decision_flags": record.get("decision_flags"),
            "founder_decision": record.get("founder_decision"),
            "updated_at": record.get("updated_at"),
        }
        if stage == "AWAITING_FOUNDER_APPROVAL":
            try:
                updated_at = datetime.fromisoformat(str(record.get("updated_at")).replace("Z", "+00:00"))
                if updated_at.tzinfo is None:
                    updated_at = updated_at.replace(tzinfo=timezone.utc)
                entry["awaiting_hours"] = round((now - updated_at).total_seconds() / 3600, 1)
                entry["stuck"] = (now - updated_at) > timedelta(hours=_STUCK_APPROVAL_HOURS)
            except (TypeError, ValueError):
                entry["awaiting_hours"] = None
                entry["stuck"] = False
            awaiting_approval.append(entry)
        entries.append(entry)

    entries.sort(key=lambda e: e.get("updated_at") or "", reverse=True)
    return {
        "stage_distribution": stage_counts,
        "awaiting_approval": awaiting_approval,
        "entries": entries,
    }
