#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Autonomous Company Evolution Engine — Evolution Queue (2026-07-29).

Real Observe -> Think -> Simulate -> Decide -> Learn pipeline for
self-improvement proposals. Execute is deliberately NOT automated here --
the founder's own explicit choice (asked directly, given this factory has
no CI/rollback safety net and no mechanism besides a real, human-observed
Claude Code session that can ever change this codebase's own files):
every proposal, regardless of computed risk tier, requires real founder
approval in Mission Control before any code is touched. Simulate/Decide
below compute a real, transparent risk/impact estimate -- they inform the
founder's review, they never bypass it.

Stage flow: PROPOSED -> SIMULATED -> AWAITING_FOUNDER_APPROVAL ->
APPROVED / REJECTED -> (once real work is later done in a reviewed
session) IMPLEMENTED. No stage past AWAITING_FOUNDER_APPROVAL is ever
reached without a real founder action -- approve_proposal()/
reject_proposal() are the only functions that can move a record there,
and neither is ever called from factory_loop.js's automatic daily tick
(see factory_loop.js's own maybeGenerateDailyEvolutionQueueIntake()).

Same "ledger vs mutable state" split this factory already uses
everywhere (decisions.jsonl vs factory_state.json; customer_requests.
jsonl vs customer_pipeline_state.json): tool_intelligence.proposals.
list_proposals() is the real, regenerated-each-call intake source (never
mutated here); data/evolution_queue_state.json is this module's own
mutable record, keyed by proposal id, carrying a real stage_history --
which IS the Learning History Dashboard item, nothing else needed.
"""

import json
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

_FACTORY_ROOT = Path(__file__).resolve().parent
DEFAULT_STATE_PATH = _FACTORY_ROOT / "data" / "evolution_queue_state.json"

# Real, named categories the directive's own "Protect" section calls out
# by name -- never touched without explicit founder approval regardless of
# any other computed risk signal. Keyword match against a proposal's own
# real evidence/tool/why_needed text (the same real strings already
# generated by tool_intelligence.proposals), not a guess.
SENSITIVE_AREA_KEYWORDS = {
    "security": ("security", "auth", "password", "token", "credential", "npm_audit", "pinning"),
    "financial": ("profit_oracle", "finance_data", "paddle", "invoice", "payment", "pricing"),
    "customer_contracts": ("contract_generator", "customer_pipeline", "accepted_name", "e-signature"),
}

# Informational only -- surfaced to the founder in list_evolution_queue(),
# never auto-escalated to any action (no notification/auto-anything).
_STUCK_APPROVAL_HOURS = 72


def _now():
    return datetime.now(timezone.utc).isoformat()


def _load_state(state_path=None):
    path = Path(state_path) if state_path else DEFAULT_STATE_PATH
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def _save_state(state, state_path=None):
    path = Path(state_path) if state_path else DEFAULT_STATE_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)


def _record_history(record, stage, detail=None):
    record["stage"] = stage
    record["updated_at"] = _now()
    record.setdefault("stage_history", []).append({"stage": stage, "at": record["updated_at"], "detail": detail})


def _new_record(proposal):
    now = _now()
    return {
        "proposal_id": proposal["id"],
        "proposal": proposal,
        "stage": "PROPOSED",
        "stage_history": [{"stage": "PROPOSED", "at": now, "detail": "real proposal intake from tool_intelligence.proposals.list_proposals()"}],
        "created_at": now,
        "updated_at": now,
        "simulation": None,
        "decision_flags": None,
        "founder_decision": None,
    }


def intake_proposals(proposals=None, state_path=None):
    """Real Observe/Think intake -- pulls tool_intelligence.proposals.
    list_proposals()'s current real output (unless a caller injects its
    own list for testing) and creates a new queue record for any real
    proposal id not already tracked. Never removes/mutates an existing
    record -- a proposal id that's already mid-review keeps its real
    history even if its generating signal later disappears."""
    if proposals is None:
        from tool_intelligence import proposals as proposals_module
        proposals = proposals_module.list_proposals()

    state = _load_state(state_path)
    added = []
    for proposal in proposals:
        pid = proposal.get("id")
        if not pid or pid in state:
            continue
        state[pid] = _new_record(proposal)
        added.append(pid)
    _save_state(state, state_path)
    return {"added_count": len(added), "added": added}


def _affected_modules(proposal):
    """Real, mechanical extraction -- every proposal already cites its
    real evidence as file/module names or dotted paths (tool_intelligence.
    proposals' own evidence-citation discipline). Extracts anything that
    looks like a real source reference; never guesses one that isn't
    textually present."""
    text = " ".join(str(proposal.get(k, "")) for k in ("evidence", "why_needed", "tool"))
    matches = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)+\b', text)
    seen = []
    for m in matches:
        if m not in seen:
            seen.append(m)
    return seen


def _sensitive_areas_touched(proposal, affected_modules):
    text = " ".join(str(proposal.get(k, "")) for k in ("evidence", "why_needed", "tool", "id")).lower()
    modules_text = " ".join(affected_modules).lower()
    touched = []
    for area, keywords in SENSITIVE_AREA_KEYWORDS.items():
        if any(kw in text or kw in modules_text for kw in keywords):
            touched.append(area)
    return touched


def simulate_proposal(proposal_id, state_path=None):
    """Real Simulate step -- a static, evidence-based impact estimate,
    never a dynamic execution this factory has no sandbox to run.
    Honestly labeled as a heuristic, not a guarantee."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "PROPOSED":
        return {"success": False, "error": f"cannot simulate from stage {record['stage']!r} (must be PROPOSED)"}

    proposal = record["proposal"]
    affected = _affected_modules(proposal)
    sensitive = _sensitive_areas_touched(proposal, affected)

    if sensitive:
        rollback_complexity = "high"
    elif len(affected) > 1:
        rollback_complexity = "medium"
    else:
        rollback_complexity = "low"

    simulation = {
        "affected_modules": affected,
        "sensitive_areas_touched": sensitive,
        "rollback_complexity": rollback_complexity,
        "method": "static evidence-text analysis -- no dynamic execution sandbox exists in this factory; this is a heuristic, not a guaranteed impact measurement",
        "simulated_at": _now(),
    }
    record["simulation"] = simulation
    _record_history(record, "SIMULATED", f"rollback_complexity={rollback_complexity}, sensitive_areas={sensitive or 'none'}")

    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def _duplicate_architecture_check(affected_modules):
    """Real, narrow check -- a proposal whose own citations already span
    3+ distinct real top-level modules covering overlapping ground is the
    one honest, mechanical signal available without semantic analysis --
    flagged for the founder to judge, never auto-decided."""
    return len({m.split(".")[0] for m in affected_modules}) >= 3


def decide_proposal(proposal_id, state_path=None):
    """Real Decide step -- computes honest concern flags and ALWAYS
    routes to AWAITING_FOUNDER_APPROVAL. Never auto-approves or
    auto-rejects: this factory has no reliable way to mechanically judge
    "does this reduce trust" or "does this break consistency" the way
    the directive names them -- surfacing the real evidence for a human
    to judge is the honest alternative to fabricating that judgment."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "SIMULATED":
        return {"success": False, "error": f"cannot decide from stage {record['stage']!r} (must be SIMULATED)"}

    simulation = record["simulation"] or {}
    affected = simulation.get("affected_modules", [])
    decision_flags = {
        "policy_risk": bool(simulation.get("sensitive_areas_touched")),
        "duplicate_architecture_risk": _duplicate_architecture_check(affected),
        "note": "Real, narrow flags only -- never an auto-approve/auto-reject. Founder approval is always required regardless of these flags.",
    }
    record["decision_flags"] = decision_flags
    _record_history(record, "AWAITING_FOUNDER_APPROVAL",
                     f"policy_risk={decision_flags['policy_risk']}, duplicate_architecture_risk={decision_flags['duplicate_architecture_risk']}")

    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def approve_proposal(proposal_id, decided_by=None, note=None, state_path=None):
    """The founder's own real action -- only valid from
    AWAITING_FOUNDER_APPROVAL. Never called automatically."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "AWAITING_FOUNDER_APPROVAL":
        return {"success": False, "error": f"cannot approve from stage {record['stage']!r} (must be AWAITING_FOUNDER_APPROVAL)"}

    record["founder_decision"] = {"decision": "APPROVED", "decided_by": decided_by, "note": note, "decided_at": _now()}
    _record_history(record, "APPROVED", note or "founder approved")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def reject_proposal(proposal_id, decided_by=None, reason=None, state_path=None):
    """The founder's own real action -- only valid from
    AWAITING_FOUNDER_APPROVAL. Never called automatically."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "AWAITING_FOUNDER_APPROVAL":
        return {"success": False, "error": f"cannot reject from stage {record['stage']!r} (must be AWAITING_FOUNDER_APPROVAL)"}

    record["founder_decision"] = {"decision": "REJECTED", "decided_by": decided_by, "reason": reason, "decided_at": _now()}
    _record_history(record, "REJECTED", reason or "founder rejected")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


def _capture_metrics_snapshot(now=None):
    """Real, source-cited snapshot across the only three post-implementation
    signals this factory can actually measure today (Autonomous Evolution
    Engine directive, 2026-07-30): revenue (channels/ledger.py's own
    real revenue_trend()), reliability (health_trend.py's own real
    GET /health snapshot history), and customer value (customer_pipeline.py's
    own real funnel_conversion_summary()). Scalability/automation/execution
    speed are deliberately NOT included -- no real signal for any of them
    exists anywhere in this factory yet (confirmed by grep before writing
    this); measure_outcome() below discloses that gap explicitly rather
    than inventing a number for it."""
    now = now or datetime.now(timezone.utc)

    from channels import ledger as sales_ledger
    revenue = sales_ledger.revenue_trend(now=now)

    import health_trend
    health_snapshots = health_trend.read_health_snapshots(limit=1)
    latest_health_status = health_snapshots[-1].get("status") if health_snapshots else None

    from customer_pipeline import funnel_conversion_summary
    funnel = funnel_conversion_summary()

    return {
        "captured_at": now.isoformat(),
        "revenue": {
            "recent_7d_revenue_usd": revenue.get("recent_7d_revenue_usd"),
            "trailing_daily_avg_usd": revenue.get("trailing_daily_avg_usd"),
            "source": "channels/ledger.py revenue_trend()",
        },
        "reliability": {
            "latest_health_status": latest_health_status,
            "source": "health_trend.py read_health_snapshots() (GET /health history)",
        },
        "customer_value": {
            "conversions": funnel.get("conversions") if funnel.get("answer") != "Unknown" else None,
            "answer": funnel.get("answer"),
            "source": "customer_pipeline.py funnel_conversion_summary()",
        },
    }


def mark_implemented(proposal_id, note=None, state_path=None, now=None):
    """Closes the loop after real work was actually done in a reviewed
    Claude Code session -- only valid from APPROVED. Never called
    automatically; this factory has no auto-apply mechanism by design.

    Autonomous Evolution Engine directive (2026-07-30): also captures a
    real baseline metrics snapshot at the moment of implementation --
    the "before" half of "continuously measures whether every implemented
    evolution actually improved [revenue/reliability/customer value]".
    Best-effort: a snapshot failure must never block the real state
    transition itself."""
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "APPROVED":
        return {"success": False, "error": f"cannot mark implemented from stage {record['stage']!r} (must be APPROVED)"}

    try:
        record["baseline_snapshot"] = _capture_metrics_snapshot(now=now)
    except Exception as exc:
        record["baseline_snapshot"] = {"error": f"فشل التقاط قياس مرجعي حقيقي: {exc}"}

    record.setdefault("outcome_measurements", [])
    _record_history(record, "IMPLEMENTED", note or "real implementation completed")
    # Stored once, explicitly -- stage_history gets a SECOND "IMPLEMENTED"
    # entry every time measure_outcome() logs a detail below, so deriving
    # "when was this really implemented" from the last matching
    # stage_history row would silently reset the elapsed-time clock on
    # every measurement. This field is the single source of truth instead.
    record["implemented_at"] = record["updated_at"]
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, **record}


# Minimum real elapsed time before a before/after comparison is trusted --
# short enough to catch a real regression reasonably soon, long enough that
# a single noisy day doesn't get reported as a real trend.
_MIN_DAYS_BEFORE_MEASURING_OUTCOME = 7


def measure_outcome(proposal_id, min_days_elapsed=_MIN_DAYS_BEFORE_MEASURING_OUTCOME, state_path=None, now=None):
    """Real Measure step (Autonomous Evolution Engine directive,
    2026-07-30): compares the real baseline_snapshot captured at
    mark_implemented() time against a fresh snapshot taken now, honestly
    reporting IMPROVED/DEGRADED/NO_CHANGE/NOT_ENOUGH_DATA per dimension --
    never a fabricated verdict. Refuses to measure before
    min_days_elapsed real days have actually passed (disclosed, not
    silently skipped). Callable repeatedly -- each real call appends a
    dated entry to the record's own outcome_measurements list, which IS
    the real trend ("continuously measures"), not a one-shot verdict."""
    now = now or datetime.now(timezone.utc)
    state = _load_state(state_path)
    record = state.get(proposal_id)
    if record is None:
        return {"success": False, "error": f"no queue record for {proposal_id!r}"}
    if record["stage"] != "IMPLEMENTED":
        return {"success": False, "error": f"cannot measure outcome from stage {record['stage']!r} (must be IMPLEMENTED)"}

    baseline = record.get("baseline_snapshot")
    if not baseline or baseline.get("error"):
        return {"success": False, "error": "لا يوجد قياس مرجعي حقيقي صالح لهذا الاقتراح (فشل عند التنفيذ)"}

    implemented_at = record.get("implemented_at")
    if implemented_at is None:
        # Fallback for a record marked IMPLEMENTED before this field
        # existed -- the FIRST real IMPLEMENTED stage_history entry (not
        # the last, which could be a later measurement's own log line).
        implemented_at = next((h["at"] for h in record.get("stage_history", []) if h["stage"] == "IMPLEMENTED"), None)
    if implemented_at is None:
        return {"success": False, "error": "لا يوجد طابع زمني حقيقي لمرحلة IMPLEMENTED"}

    try:
        implemented_dt = datetime.fromisoformat(implemented_at.replace("Z", "+00:00"))
    except ValueError:
        return {"success": False, "error": "طابع زمني غير صالح لمرحلة IMPLEMENTED"}

    elapsed_days = (now - implemented_dt).total_seconds() / 86400
    if elapsed_days < min_days_elapsed:
        return {
            "success": False,
            "not_enough_time": True,
            "elapsed_days": round(elapsed_days, 1),
            "min_days_elapsed": min_days_elapsed,
            "reason": f"مضى {elapsed_days:.1f} يوم فقط منذ التنفيذ الحقيقي -- يلزم {min_days_elapsed} يوم على الأقل لمقارنة موثوقة",
        }

    current = _capture_metrics_snapshot(now=now)

    def _compare(dim, base_val, cur_val):
        if base_val is None or cur_val is None:
            return "NOT_ENOUGH_DATA"
        if isinstance(base_val, (int, float)) and isinstance(cur_val, (int, float)):
            if cur_val > base_val:
                return "IMPROVED"
            if cur_val < base_val:
                return "DEGRADED"
            return "NO_CHANGE"
        return "NOT_ENOUGH_DATA"

    revenue_verdict = _compare(
        "revenue",
        baseline["revenue"].get("trailing_daily_avg_usd"),
        current["revenue"].get("trailing_daily_avg_usd"),
    )
    reliability_order = {"healthy": 0, "degraded": 1, "critical": 2}
    base_rel = reliability_order.get(baseline["reliability"].get("latest_health_status"))
    cur_rel = reliability_order.get(current["reliability"].get("latest_health_status"))
    if base_rel is None or cur_rel is None:
        reliability_verdict = "NOT_ENOUGH_DATA"
    elif cur_rel < base_rel:
        reliability_verdict = "IMPROVED"
    elif cur_rel > base_rel:
        reliability_verdict = "DEGRADED"
    else:
        reliability_verdict = "NO_CHANGE"

    measurement = {
        "measured_at": now.isoformat(),
        "elapsed_days": round(elapsed_days, 1),
        "baseline": baseline,
        "current": current,
        "verdicts": {
            "revenue": revenue_verdict,
            "reliability": reliability_verdict,
            "customer_value": "NOT_ENOUGH_DATA" if current["customer_value"].get("answer") == "Unknown" else "SEE_CONVERSIONS",
            "scalability": "NO_REAL_SIGNAL -- لا يوجد مقياس قابلية توسّع حقيقي في هذا المصنع بعد",
            "automation": "NO_REAL_SIGNAL -- لا يوجد مقياس أتمتة حقيقي في هذا المصنع بعد",
            "execution_speed": "NO_REAL_SIGNAL -- لا يوجد مقياس سرعة تنفيذ حقيقي مرتبط بمقترحات فردية بعد",
        },
        "method": "مقارنة حقيقية قبل/بعد لإشارات فعلية مسجَّلة فقط -- لا تنبّؤ، لا تقدير لأي بُعد بلا مصدر حقيقي",
    }

    record.setdefault("outcome_measurements", []).append(measurement)
    _record_history(record, "IMPLEMENTED", f"outcome measured: revenue={revenue_verdict}, reliability={reliability_verdict}")
    state[proposal_id] = record
    _save_state(state, state_path)
    return {"success": True, "proposal_id": proposal_id, "measurement": measurement}


def run_daily_outcome_measurement_cycle(state_path=None, now=None, min_days_elapsed=_MIN_DAYS_BEFORE_MEASURING_OUTCOME):
    """The only automatic path for Measure -- runs measure_outcome() for
    every real IMPLEMENTED record. Read-only against every stage/decision
    field; only ever appends to outcome_measurements. Honestly skips (not
    silently) any record still under min_days_elapsed."""
    state = _load_state(state_path)
    measured, skipped = [], []
    for pid, record in state.items():
        if record["stage"] != "IMPLEMENTED":
            continue
        result = measure_outcome(pid, min_days_elapsed=min_days_elapsed, state_path=state_path, now=now)
        if result.get("success"):
            measured.append(pid)
        else:
            skipped.append({"proposal_id": pid, "reason": result.get("reason", result.get("error"))})
    return {"measured_count": len(measured), "measured": measured, "skipped": skipped}


def list_measured_outcomes(state_path=None):
    """Mission Control aggregate -- every real IMPLEMENTED proposal's
    latest measurement (or an honest NOT_YET_MEASURED/AWAITING_MIN_
    ELAPSED_TIME) plus its full real measurement history (the actual
    trend, not just a snapshot)."""
    state = _load_state(state_path)
    entries = []
    for pid, record in state.items():
        if record["stage"] != "IMPLEMENTED":
            continue
        measurements = record.get("outcome_measurements", [])
        entries.append({
            "proposal_id": pid,
            "tool": record["proposal"].get("tool"),
            "implemented_at": record.get("implemented_at"),
            "measurement_count": len(measurements),
            "latest_measurement": measurements[-1] if measurements else None,
            "status": "MEASURED" if measurements else "NOT_YET_MEASURED",
        })
    entries.sort(key=lambda e: e.get("implemented_at") or "", reverse=True)
    return {"entries": entries}


# Real keyword tags, same discipline as SENSITIVE_AREA_KEYWORDS above --
# never a semantic classifier, just a disclosed, mechanical text match.
_REVENUE_KEYWORDS = ("عميل", "customer", "إيراد", "revenue", "مبيع", "sale", "دفع", "payment", "نشر", "publish")


def rank_proposal(record):
    """Real Rank step (Autonomous Evolution Engine directive, 2026-07-30):
    a disclosed heuristic over fields this record ALREADY has (simulation/
    decision_flags/proposal text) -- never a fabricated numeric priority
    score. strategic_value is honestly reported as not computed: no
    per-proposal strategic-value signal exists anywhere in this factory
    today (strategic_intelligence_core.strategic_score() is per-niche,
    not per-proposal, and most evolution proposals are company-wide)."""
    proposal = record.get("proposal", {})
    simulation = record.get("simulation") or {}
    decision_flags = record.get("decision_flags") or {}

    text = " ".join(str(proposal.get(k, "")) for k in ("why_needed", "evidence", "tool")).lower()
    revenue_impact = "revenue_linked" if any(kw in text for kw in _REVENUE_KEYWORDS) else "not_revenue_linked"

    execution_cost = simulation.get("rollback_complexity", "unknown")

    unknown_marker = "غير مقاس بعد"
    known_fields = sum(
        1 for k in ("estimated_roi", "implementation_effort")
        if unknown_marker not in str(proposal.get(k, ""))
    )
    confidence = "partial_real_data" if known_fields else "estimate_only"

    if decision_flags.get("policy_risk") or execution_cost == "high":
        risk = "high"
    elif execution_cost == "medium":
        risk = "medium"
    elif execution_cost == "low":
        risk = "low"
    else:
        risk = "unknown"

    return {
        "strategic_value": {"value": "not_computed", "reason": "لا يوجد مقياس قيمة استراتيجية على مستوى المقترح الفردي في هذا المصنع بعد"},
        "revenue_impact": revenue_impact,
        "execution_cost": execution_cost,
        "long_term_sustainability_concern": bool(decision_flags.get("duplicate_architecture_risk")),
        "risk": risk,
        "confidence": confidence,
        "method": "ترتيب استدلالي مُفصَح عنه فوق حقول حقيقية موجودة بالفعل (evidence keywords، rollback_complexity، decision_flags) -- ليس درجة أولوية رقمية مُختلَقة",
    }


def run_daily_cycle(proposals=None, state_path=None):
    """The only automatic path -- Observe/Think/Simulate/Decide, real and
    safe (pure analysis, no execution). Every record this touches stops
    at AWAITING_FOUNDER_APPROVAL at the latest; approve_proposal()/
    reject_proposal()/mark_implemented() are never called from here."""
    intake_result = intake_proposals(proposals=proposals, state_path=state_path)
    processed = []
    for pid in intake_result["added"]:
        simulate_proposal(pid, state_path=state_path)
        decide_proposal(pid, state_path=state_path)
        processed.append(pid)
    return {"added_count": intake_result["added_count"], "processed": processed}


def list_evolution_queue(state_path=None, now=None):
    """Mission Control aggregate -- real stage distribution, the real
    awaiting-approval queue (with a real, informational stuck-too-long
    flag), and the full real Learning History (every record's own
    stage_history, nothing summarized away)."""
    now = now or datetime.now(timezone.utc)
    state = _load_state(state_path)
    stage_counts = {}
    awaiting_approval = []
    entries = []
    for pid, record in state.items():
        stage = record["stage"]
        stage_counts[stage] = stage_counts.get(stage, 0) + 1
        entry = {
            "proposal_id": pid,
            "tool": record["proposal"].get("tool"),
            "stage": stage,
            "simulation": record.get("simulation"),
            "decision_flags": record.get("decision_flags"),
            "founder_decision": record.get("founder_decision"),
            "updated_at": record.get("updated_at"),
            "ranking": rank_proposal(record) if record.get("simulation") else None,
        }
        if stage == "AWAITING_FOUNDER_APPROVAL":
            try:
                updated_at = datetime.fromisoformat(str(record.get("updated_at")).replace("Z", "+00:00"))
                if updated_at.tzinfo is None:
                    updated_at = updated_at.replace(tzinfo=timezone.utc)
                entry["awaiting_hours"] = round((now - updated_at).total_seconds() / 3600, 1)
                entry["stuck"] = (now - updated_at) > timedelta(hours=_STUCK_APPROVAL_HOURS)
            except (TypeError, ValueError):
                entry["awaiting_hours"] = None
                entry["stuck"] = False
            awaiting_approval.append(entry)
        entries.append(entry)

    entries.sort(key=lambda e: e.get("updated_at") or "", reverse=True)
    return {
        "stage_distribution": stage_counts,
        "awaiting_approval": awaiting_approval,
        "entries": entries,
    }
