#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Commercial Execution Engine v1 (ADR-180, 2026-08-06) — the founder's
directive to generalize the hand-written EU AI Act Compliance Toolkit
launch kit (books/eu_ai_act_compliance_toolkit_launch_kit.md) into a
reusable template engine, wired to auto-generate for every future real
ACCEPTED opportunity.

Named `product_marketing_engine.py`, not `commercial_execution.py` or
`commercial_engine.py`: a real `commercial_execution/` package already
exists (Universal Production Engine Roadmap Step 4, 2026-07-19) — but it
answers a completely different question ("how does an already-built
product get distributed, verified, and revenue-registered") from this
directive ("what marketing content should a product have before it's
published"). `commercial_intelligence.py` also already exists (real
demand/WTP/competition/price-range signals) and is reused here directly,
never re-derived. Same naming-collision discipline this factory has
applied repeatedly this session (growth_stages.py/growth_engine.py,
executive_questions.py/executive_intelligence/) — checked before writing
a single line of this file.

Real facts in, real AI-generated copy out: every section is generated by
one real `ai_capability.orchestrator.generate()` call (task_type
"writing" — the real, named multi-model routing entrypoint, currently
resolving to Groq, the same mechanism `market_intelligence_engine.py`'s
`reformulate_pain_query()` already proved end-to-end) seeded with real
product facts (title, real price, real competitor citations from
`commercial_intelligence.py`, real audience) — never a hardcoded English
template blindly reused across wildly different products. Every
generated kit is run through `brand_dna.validate_customer_facing_text()`
before being recorded — the real, existing Trust Framework enforcement
point, not a second QA gate invented here.

Auto-generation mirrors `autonomous_business_builder.py::
generate_pending_business_blueprints()`'s exact real pattern: for every
real ACCEPTED decision without an already-recorded kit, generate up to
`limit` new ones per call (bounding real Groq cost), dedup against a
real append-only ledger (`data/generated_commercial_kits.jsonl`, same
one-record-per-line convention as `data/generated_business_blueprints.jsonl`).
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path

_FACTORY_ROOT = Path(__file__).resolve().parent
DEFAULT_LEDGER_PATH = _FACTORY_ROOT / "data" / "generated_commercial_kits.jsonl"

# The founder's own 12 named sections (Commercial Execution Engine
# directive, 2026-08-06) -- the canonical vocabulary every generated kit
# is parsed into. Order matches the directive's own list.
SECTION_NAMES = (
    "positioning", "pricing_strategy", "gumroad_page", "sales_page",
    "seo_package", "tags", "launch_checklist", "marketing_assets",
    "email_campaign", "social_media_campaign", "customer_acquisition_plan",
    "continuous_optimization_plan",
)

_SYSTEM_PROMPT = """You are Galaxy Forge's Commercial Execution Engine. You produce launch-ready commercial content for one real digital product, using only the real facts given to you -- never invented sales counts, testimonials, reviews, or urgency claims. Where you have no real fact to cite (e.g. no real reviews exist yet), write "[PLACEHOLDER -- populate only once real data exists]" instead of inventing one.

Produce exactly these 12 sections, each starting with a markdown header in this exact form: "## N. SECTION_NAME" (use the literal SECTION_NAME tokens given below, uppercase, underscores as shown):

## 1. POSITIONING
## 2. PRICING_STRATEGY
## 3. GUMROAD_PAGE
## 4. SALES_PAGE
## 5. SEO_PACKAGE
## 6. TAGS
## 7. LAUNCH_CHECKLIST
## 8. MARKETING_ASSETS
## 9. EMAIL_CAMPAIGN
## 10. SOCIAL_MEDIA_CAMPAIGN
## 11. CUSTOMER_ACQUISITION_PLAN
## 12. CONTINUOUS_OPTIMIZATION_PLAN

Each section should be concrete and specific to the real product facts given -- never generic filler that could apply to any product. Write in English (the real target platforms are English-language)."""


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def _gather_real_product_facts(niche, price=None, title=None, audience=None,
                                decisions_path=None, board_path=None, alerts_path=None,
                                reopen_log_path=None, evidence_path=None):
    """Real citation layer only -- reuses commercial_intelligence.py's
    already-real demand/willingness-to-pay/competition/price-range/
    buying-behavior/customer-pain report and decision_engine's own
    record, never a second market-research pass. Every field is
    honestly None/Unknown when no real signal exists, matching this
    factory's established discipline everywhere else."""
    import commercial_intelligence

    intel = commercial_intelligence.build_commercial_intelligence_report(
        niche, decisions_path=decisions_path, board_path=board_path,
        alerts_path=alerts_path, reopen_log_path=reopen_log_path, evidence_path=evidence_path,
    )

    resolved_price = price
    if resolved_price is None and intel:
        this_price = (intel.get("price_ranges") or {}).get("this_decision_price")
        if isinstance(this_price, (int, float)):
            resolved_price = this_price

    return {
        "niche": niche,
        "title": title or niche,
        "price": resolved_price,
        "audience": audience,
        "commercial_intelligence": intel,
    }


def _build_prompt(facts):
    intel = facts.get("commercial_intelligence") or {}
    price_line = f"${facts['price']}" if facts.get("price") is not None else "Unknown -- suggest a real, justified price in PRICING_STRATEGY based on the signals below"
    lines = [
        f"Product title: {facts['title']}",
        f"Niche/topic: {facts['niche']}",
        f"Price: {price_line}",
        f"Target audience: {facts.get('audience') or 'Unknown -- infer the most plausible real buyer persona from the niche itself'}",
    ]
    if intel:
        lines.append(f"Real demand signal: {json.dumps(intel.get('demand'), ensure_ascii=False, default=str)}")
        lines.append(f"Real willingness-to-pay signal: {json.dumps(intel.get('willingness_to_pay'), ensure_ascii=False, default=str)}")
        lines.append(f"Real competition signal: {json.dumps(intel.get('competition'), ensure_ascii=False, default=str)}")
        lines.append(f"Real price range for this ladder: {json.dumps(intel.get('price_ranges'), ensure_ascii=False, default=str)}")
        lines.append(f"Real customer pain signal: {json.dumps(intel.get('customer_pain'), ensure_ascii=False, default=str)}")
    else:
        lines.append("No real commercial_intelligence report exists yet for this niche (no decision on record) -- work only from the title/niche/price/audience above, and say so explicitly wherever you'd otherwise need a market signal you don't have.")
    return "\n".join(lines)


def _parse_commercial_kit_sections(raw_text):
    """Same header-splitting technique book_generator.py's own
    _parse_sectioned_book() established: small/instant models reliably
    emit '## heading' markdown but not always exact literal tags, so
    this matches by keyword against SECTION_NAMES rather than requiring
    byte-exact headers."""
    parts = re.split(r'(?m)^#{1,4}\s*\d*\.?\s*(.+?)\s*#{0,4}\s*$', raw_text)
    sections = {name: "" for name in SECTION_NAMES}
    # re.split with a capturing group returns [pre, header1, body1, header2, body2, ...]
    for i in range(1, len(parts) - 1, 2):
        header = parts[i].strip().lower().replace(" ", "_").replace("-", "_")
        body = parts[i + 1].strip()
        for name in SECTION_NAMES:
            if name in header:
                sections[name] = body
                break
    return sections


def generate_commercial_kit(niche, price=None, title=None, audience=None,
                             decisions_path=None, board_path=None, alerts_path=None,
                             reopen_log_path=None, evidence_path=None, cost_log_path=None,
                             max_tokens=6000):
    """The one real generation call. Produces all 12 named sections from
    real product facts via ai_capability.orchestrator.generate() (task_
    type "writing" -- this factory's real, named multi-model routing
    entrypoint, never a direct/duplicate Groq call). Every generated kit
    is run through brand_dna.validate_customer_facing_text() before
    being returned -- the real, existing Trust Framework enforcement
    point."""
    import ai_capability.orchestrator as ai_orch
    import brand_dna

    facts = _gather_real_product_facts(
        niche, price=price, title=title, audience=audience,
        decisions_path=decisions_path, board_path=board_path, alerts_path=alerts_path,
        reopen_log_path=reopen_log_path, evidence_path=evidence_path,
    )
    user_prompt = _build_prompt(facts)
    result = ai_orch.generate(
        "writing", _SYSTEM_PROMPT, user_prompt,
        max_tokens=max_tokens, cost_context={"niche": niche, "purpose": "commercial_execution_kit"},
        cost_log_path=cost_log_path,
    )
    raw_content = result["content"]
    sections = _parse_commercial_kit_sections(raw_content)
    brand_check = brand_dna.validate_customer_facing_text(raw_content)

    return {
        "niche": niche,
        "facts": facts,
        "sections": sections,
        "raw_content": raw_content,
        "provider": result["provider"],
        "brand_check": brand_check,
        "generated_at": _now_iso(),
    }


def render_commercial_kit_markdown(kit):
    """Deterministic, mechanical rendering of an already-generated kit --
    same convention as evolution_engine.py/ai_doctor.py's own
    render_markdown(): every line is a direct read of a real field
    above, never freely-generated text at render time (the generation
    already happened in generate_commercial_kit())."""
    lines = [f"# Commercial Execution Kit — {kit['facts']['title']}", ""]
    brand_status = "PASSED" if kit["brand_check"].get("passed") else f"FAILED ({', '.join(kit['brand_check'].get('failed_checks', []))})"
    lines.append(f"Generated: {kit['generated_at']} | Provider: {kit['provider']} | Brand check: {brand_status}")
    lines.append("")
    for i, name in enumerate(SECTION_NAMES, 1):
        lines.append(f"## {i}. {name.upper()}")
        lines.append(kit["sections"].get(name) or "_[not generated -- parser found no matching section]_")
        lines.append("")
    return "\n".join(lines)


def pending_commercial_kits_status(decisions_path=None, ledger_path=None):
    """Read-only, zero-cost citation for executive_brain.py -- counts
    real ACCEPTED decisions without a generated kit yet, WITHOUT ever
    calling generate_commercial_kit() (which spends real Groq cost).
    Never triggered from inside the Brain itself; the Brain only cites
    this count, exactly the same "read-only injection, real generation
    stays in the daily tick" discipline sie/commercial_kits both follow
    in executive_brain.py::_candidate_directives()."""
    from decision_engine import ranking

    accepted = [d for d in ranking.rank_all(path=decisions_path) if d.get("status") == "ACCEPTED" and d.get("niche")]
    already_covered = _read_generated_kit_niches(ledger_path)
    remaining = [d for d in accepted if d["niche"] not in already_covered]
    return {
        "total_accepted": len(accepted),
        "generated": [],
        "remaining_pending": len(remaining),
        "generated_at": _now_iso(),
    }


def _read_generated_kit_niches(path=None):
    path = Path(path) if path else DEFAULT_LEDGER_PATH
    if not path.exists():
        return set()
    niches = set()
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                niches.add(json.loads(line)["niche"])
            except (json.JSONDecodeError, KeyError):
                continue
    return niches


def _record_generated_kit(niche, decision_id, path=None):
    record = {"niche": niche, "decision_id": decision_id, "generated_at": _now_iso()}
    out_path = Path(path) if path else DEFAULT_LEDGER_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")
    return record


def generate_pending_commercial_kits(limit=2, decisions_path=None, ledger_path=None,
                                      board_path=None, alerts_path=None, reopen_log_path=None,
                                      evidence_path=None):
    """For every real ACCEPTED decision without an already-recorded
    commercial kit, generates and records up to `limit` new ones this
    call -- bounding real Groq cost per call regardless of how many
    real ACCEPTED decisions exist. Safe to call every real tick: the
    dedup check is cheap; cost is only incurred for genuinely new, real
    ACCEPTED niches. Exact mirror of autonomous_business_builder.py::
    generate_pending_business_blueprints()'s real pattern."""
    from decision_engine import ranking

    accepted = [d for d in ranking.rank_all(path=decisions_path) if d.get("status") == "ACCEPTED" and d.get("niche")]
    already_covered = _read_generated_kit_niches(ledger_path)
    pending = [d for d in accepted if d["niche"] not in already_covered]

    generated = []
    for decision in pending[:max(0, limit)]:
        niche = decision["niche"]
        kit = generate_commercial_kit(
            niche, price=decision.get("evaluation_snapshot", {}).get("pricing", {}).get("recommended_price"),
            decisions_path=decisions_path, board_path=board_path, alerts_path=alerts_path,
            reopen_log_path=reopen_log_path, evidence_path=evidence_path,
        )
        _record_generated_kit(niche, decision.get("decision_id"), ledger_path)
        generated.append({"niche": niche, "decision_id": decision.get("decision_id")})

    return {
        "total_accepted": len(accepted),
        "generated": generated,
        "remaining_pending": max(0, len(pending) - len(generated)),
        "generated_at": _now_iso(),
    }


def list_generated_commercial_kits(limit=20, ledger_path=None):
    """Mission Control read-model -- real ledger passthrough, most
    recent first."""
    path = Path(ledger_path) if ledger_path else DEFAULT_LEDGER_PATH
    if not path.exists():
        return {"entries": [], "count": 0}
    entries = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    entries.reverse()
    return {"entries": entries[:limit], "count": len(entries)}
